@extends('layouts.app')
@section('content')
    <header class="wisata-hero" id="heroSection"
        style="background-image: url('https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxXdiswzGOKnBQxI9_PrlRx9JURBHHxAnInt7x2hJakl49ED_jI9yDTIDAOI_atF47x_Npvx-x83_D-xNeC_CGptilMjYzXDEISGfj0a5vfl8zFOZvfVZEXb8TBnU8p1DQbzok=s1360-w1360-h1020-rw');">

        <div class="hero-content-wrapper">

            <!-- KIRI BAWAH: Judul & Teks -->
            <div class="hero-text-box" id="heroTextBox">
                <h1 id="heroTitle">Hutan Joyoboyo</h1>
                <p id="heroDesc">
                    Hutan Kota Joyoboyo, yang sebagian areanya diperuntukkan sebagai Taman Hutan Joyoboyo adalah ruang terbuka hijau yang terletak di Kota Kediri, Jawa Timur.
                </p>
                <a href="#explore" class="explore-btn">
                    Explore Now <span class="material-symbols-outlined">arrow_forward</span>
                </a>
            </div>

            <!-- KANAN BAWAH: Card Slider -->
            <div class="hero-slider-box">
                <div class="card-slider" id="cardSlider">
                    <!-- Cards -->
                    <div class="slide-card active" data-index="0" data-title="Hutan Joyoboyo"
                        data-desc="Rasakan sensasi petualangan di puncak gunung berapi aktif yang menawarkan panorama kawah hijau tosca yang memukau."
                        data-bg="https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxXdiswzGOKnBQxI9_PrlRx9JURBHHxAnInt7x2hJakl49ED_jI9yDTIDAOI_atF47x_Npvx-x83_D-xNeC_CGptilMjYzXDEISGfj0a5vfl8zFOZvfVZEXb8TBnU8p1DQbzok=s1360-w1360-h1020-rw">
                        <img src="https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxXdiswzGOKnBQxI9_PrlRx9JURBHHxAnInt7x2hJakl49ED_jI9yDTIDAOI_atF47x_Npvx-x83_D-xNeC_CGptilMjYzXDEISGfj0a5vfl8zFOZvfVZEXb8TBnU8p1DQbzok=s1360-w1360-h1020-rw">
                        <div class="slide-card-info">Hutan Joyoboyo</div>
                    </div>

                    <div class="slide-card" data-index="1" data-title="Taman Brantas"
                        data-desc="Monumen ikonik yang menyerupai Arc de Triomphe di Paris. Pusat keramaian, fotografi, dan kuliner malam hari di Kediri."
                        data-bg="https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxk3Jgx6W32AygkRbXbmP0aTgdn0z9jNY0E57ZCZNTEumNY86wZqMqI9RfJqlz_xwCbEY9ip3coSYn8VgQgz6zRiNeaDWh0oi_ez-IHOvct5SsHMVhBeHrPvXTKBfy9DTTc210=s1360-w1360-h1020-rw">
                        <img src="https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxk3Jgx6W32AygkRbXbmP0aTgdn0z9jNY0E57ZCZNTEumNY86wZqMqI9RfJqlz_xwCbEY9ip3coSYn8VgQgz6zRiNeaDWh0oi_ez-IHOvct5SsHMVhBeHrPvXTKBfy9DTTc210=s1360-w1360-h1020-rw">
                        <div class="slide-card-info">Taman Brantas</div>
                    </div>

                    <div class="slide-card" data-index="2" data-title="Taman Sekartaji"
                        data-desc="Situs bersejarah tempat pertapaan Dewi Kilisuci. Nikmati wisata budaya dan alam sekaligus di kaki Gunung Klotok."
                        data-bg="https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyXnjK_Sufh8fuyDl5cC2P6-qNtXQXdBQoHJoxHd9-5D4d-eJ9zPGUaL-BoIqoyILXaMv56C_rj4waqDTidO9JtaJVcFm8EXG7i5WHS6sLmPsseEqaszVXs8XbhG93GJGkX7330PA=s1360-w1360-h1020-rw">
                        <img src="https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyXnjK_Sufh8fuyDl5cC2P6-qNtXQXdBQoHJoxHd9-5D4d-eJ9zPGUaL-BoIqoyILXaMv56C_rj4waqDTidO9JtaJVcFm8EXG7i5WHS6sLmPsseEqaszVXs8XbhG93GJGkX7330PA=s1360-w1360-h1020-rw">
                        <div class="slide-card-info">Taman Sekartaji</div>
                    </div>

                    <div class="slide-card" data-index="3" data-title="Goa Selomangkleng"
                        data-desc="Taman kota modern di tepi Sungai Brantas. Tempat sempurna untuk bersantai sore, jogging, dan menikmati senja."
                        data-bg="{{ asset('image/goa.webp') }}">
                        <img src="{{ asset('image/goa.webp') }}">
                        <div class="slide-card-info">Goa Selomangleng</div>
                    </div>
                </div>
            </div>
        </div>

        <!-- PAGINATION DOTS (BARU) -->
        <div class="hero-pagination" id="heroPagination">
            <!-- Dots will be generated by JS -->
        </div>

    </header>

    <section class="nearby-section" id="explore">
        <div class="nearby-container">
            <div class="nearby-header">
                <h2>Cari Tempat di sekitarmu</h2>
                <p>Temukan berbagai lokasi penting di Kota Kediri seperti tempat wisata, kuliner, sekolah, universitas,
                    fasilitas kota, rental kendaraan, hingga pondok pesantren. Pilih kategori yang kamu butuhkan dan
                    jelajahi dengan cepat dan mudah.</p>
            </div>

            <div class="nearby-filters">
                <button class="filter-btn active" data-filter="wisata">Wisata</button>
                <button class="filter-btn" data-filter="fasilitas">Fasilitas Kota</button>
                <button class="filter-btn" data-filter="transportasi">Transport & Rental</button>
            </div>

            <div class="nearby-map">
                <iframe
                    src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d63261.94228965021!2d111.97905342167968!3d-7.82823379999999!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1swisata%20di%20Kediri!5e0!3m2!1sen!2sid!4v1731295000000!5m2!1sen!2sid"
                    allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade">
                </iframe>
            </div>

            <!-- INFO SEKITAR (BARU) -->
            <div class="nearby-info-grid">

                <!-- Item 1: Populer -->
                <div class="nearby-info-item">
                    <div class="info-icon-circle">
                        <span class="material-symbols-outlined">location_on</span>
                    </div>
                    <div class="info-text-wrapper">
                        <h4>Populer didekatmu</h4>
                        <p>Tempat-tempat yang paling sering dikunjungi wisatawan minggu ini. Pastikan Anda tidak
                            melewatkannya.</p>
                    </div>
                </div>

                <!-- Item 2: Favorite -->
                <div class="nearby-info-item">
                    <div class="info-icon-circle">
                        <span class="material-symbols-outlined">favorite</span>
                    </div>
                    <div class="info-text-wrapper">
                        <h4>Favorite didekatmu</h4>
                        <p>Destinasi dengan rating tertinggi dan ulasan terbaik dari pengunjung yang pernah datang ke sini.
                        </p>
                    </div>
                </div>

                <!-- Item 3: Ramai -->
                <div class="nearby-info-item">
                    <div class="info-icon-circle">
                        <span class="material-symbols-outlined">groups</span>
                    </div>
                    <div class="info-text-wrapper">
                        <h4>Ramai di dekatmu</h4>
                        <p>Lokasi yang sedang padat pengunjung saat ini. Rasakan keramaian dan keseruannya secara langsung.
                        </p>
                    </div>
                </div>

            </div>

        </div>
    </section>
    <main class="main-container" id="main-content">

        <h2 class="section-title">Sejarah Populer Lainnya</h2>

        <!-- Grid 10 Kartu -->
        <div class="history-grid">

            <!-- Card 1 -->
            <div class="history-card">
                <div class="history-card-img-wrapper">
                    <img src="https://placehold.co/400x500/0D7DA3/white?text=>Lebak Tumpang" alt="Lebak Tumpang"
                        class="history-card-img">
                </div>
                <div class="history-card-content">
                    <h4 class="history-card-title">Lebak Tumpang</h4>
                    <div class="history-card-location">Kec. Mojoroto</div>
                </div>
            </div>

            <!-- Card 2 -->
            <div class="history-card">
                <div class="history-card-img-wrapper">
                    <img src="https://placehold.co/400x500/1E90FF/white?text=Taman Ngronggo" alt="Taman Ngronggo"
                        class="history-card-img">
                </div>
                <div class="history-card-content">
                    <h4 class="history-card-title">Taman Ngronggo</h4>
                    <div class="history-card-location">Kec. Kota</div>
                </div>
            </div>

            <!-- Card 3 -->
            <div class="history-card">
                <div class="history-card-img-wrapper">
                    <img src="https://placehold.co/400x500/FFD700/333?text=Tritoyoso Park" alt="Tritoyoso Park"
                        class="history-card-img">
                </div>
                <div class="history-card-content">
                    <h4 class="history-card-title">Tritoyoso Park</h4>
                    <div class="history-card-location">Kec. Kota</div>
                </div>
            </div>

            <!-- Card 4 -->
            <div class="history-card">
                <div class="history-card-img-wrapper">
                    <img src="https://placehold.co/400x500/333/white?text=Jembatan+Lama" alt="Jembatan Lama"
                        class="history-card-img">
                </div>
                <div class="history-card-content">
                    <h4 class="history-card-title">Jembatan Lama Brantas</h4>
                    <div class="history-card-location">Kota Kediri</div>
                </div>
            </div>

            <!-- Card 5 -->
            <div class="history-card">
                <div class="history-card-img-wrapper">
                    <img src="https://placehold.co/400x500/a057d3/white?text=Masjid+Agung" alt="Masjid Agung"
                        class="history-card-img">
                </div>
                <div class="history-card-content">
                    <h4 class="history-card-title">Masjid Agung Kota Kediri</h4>
                    <div class="history-card-location">Alun-Alun Kota</div>
                </div>
            </div>

            <!-- Card 6 -->
            <div class="history-card">
                <div class="history-card-img-wrapper">
                    <img src="https://placehold.co/400x500/57a0d3/white?text=Klenteng" alt="Klenteng Tjoe Hwie Kiong"
                        class="history-card-img">
                </div>
                <div class="history-card-content">
                    <h4 class="history-card-title">Klenteng Tjoe Hwie Kiong</h4>
                    <div class="history-card-location">Jl. Yos Sudarso</div>
                </div>
            </div>

            <!-- Card 7 -->
            <div class="history-card">
                <div class="history-card-img-wrapper">
                    <img src="https://placehold.co/400x500/d357a0/white?text=Gereja+Merah" alt="Gereja Merah"
                        class="history-card-img">
                </div>
                <div class="history-card-content">
                    <h4 class="history-card-title">Gereja Merah</h4>
                    <div class="history-card-location">Bandar Lor</div>
                </div>
            </div>

            <!-- Card 8 -->
            <div class="history-card">
                <div class="history-card-img-wrapper">
                    <img src="https://placehold.co/400x500/a0d357/white?text=Taman Air Pagora" alt="Taman Air Pagora"
                        class="history-card-img">
                </div>
                <div class="history-card-content">
                    <h4 class="history-card-title">Taman Air Pagora</h4>
                    <div class="history-card-location">Kec. Kota</div>
                </div>
            </div>

            <!-- Card 9 -->
            <div class="history-card">
                <div class="history-card-img-wrapper">
                    <img src="https://placehold.co/400x500/d3a057/white?text=Makam+Aulia" alt="Makam Aulia Setono Gedong"
                        class="history-card-img">
                </div>
                <div class="history-card-content">
                    <h4 class="history-card-title">Makam Setono Gedong</h4>
                    <div class="history-card-location">Setono Gedong</div>
                </div>
            </div>

            <!-- Card 10 -->
            <div class="history-card">
                <div class="history-card-img-wrapper">
                    <img src="https://placehold.co/400x500/57d3a0/white?text=Totok+Kerot" alt="Taman Sekartaji"
                        class="history-card-img">
                </div>
                <div class="history-card-content">
                    <h4 class="history-card-title">Taman Sekartaji</h4>
                    <div class="history-card-location">Kec. Kota</div>
                </div>
            </div>

        </div>
    </main>
@endsection
